try {
    
    console.log(naoExisto);
} catch(error) {
    console.log('naoExito n√£o existe');
    console.log(err); // jaamis exiba o erro para o usuario final sempre trate o erro
}